Revert "build(rocjitsu): add rocjitsu to therock build system" (#5033)
Reverts ROCm/TheRock#4942

Broke the build:
https://github.com/ROCm/TheRock/actions/runs/25344864053/job/74312073259#step:15:181
```

82/84 Test #82: therock-validate-shared-lib-librocprofv3-list-avail.so ...........   Passed    0.05 sec
      Start 83: therock-validate-shared-lib-librocjitsu.so
83/84 Test #83: therock-validate-shared-lib-librocjitsu.so .......................***Failed    0.03 sec
Validating shared library: /__w/TheRock/TheRock/build/emulation/rocjitsu/dist/lib/librocjitsu.soTraceback (most recent call last):
  File "/__w/TheRock/TheRock/build_tools/validate_shared_library.py", line 27, in <module>
    main(sys.argv[1:])
  File "/__w/TheRock/TheRock/build_tools/validate_shared_library.py", line 23, in main
    run(args)
  File "/__w/TheRock/TheRock/build_tools/validate_shared_library.py", line 15, in run
    so = ctypes.cdll.LoadLibrary(shared_lib)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/cp312-cp312/lib/python3.12/ctypes/__init__.py", line 460, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/python/cp312-cp312/lib/python3.12/ctypes/__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: /__w/TheRock/TheRock/build/emulation/rocjitsu/dist/lib/librocjitsu.so: undefined symbol: _ZNK8rocjitsu16RegisterLiveness19find_free_sgpr_pairEt

      Start 84: therock-examples-cpp-sdk-user
84/84 Test #84: therock-examples-cpp-sdk-user ....................................   Passed    3.99 sec

99% tests passed, 1 tests failed out of 84

Total Test time (real) =   5.86 sec

The following tests FAILED:
	 83 - therock-validate-shared-lib-librocjitsu.so (Failed)
Errors while running CTest
Error: Process completed with exit code 8.
```